---
mysql/mysql-5.6.13.tar.gz:
  object_id: 4afe18ad-4f66-4109-a1a1-0e36c97eb318
  sha: !binary |-
    MDZlMWQ4NTZjZmIxZjk4ODQ0ZWY5MmFmNDdkNGY0ZjcwMzZlZjI5NA==
  size: 35951160
mysqlclient/mysql-connector-c-6.1.1-src.tar.gz:
  object_id: 4568da3d-5618-4a7c-9afa-b4eda9f82cd5
  sha: !binary |-
    OGEwMDE0YWQzNGQwZWE5OGMzMTA0ZGM4ZTg2M2UwNjIyNTk3MTk0Yw==
  size: 3031012
ruby/bundler-1.3.5.gem:
  object_id: 7eba9228-785f-42b7-8315-9fe10f04e249
  sha: !binary |-
    MmNhZDMwNTJhNTliODNmMWY2MTZlODIwMmY1YzcxNGU0NmJkODUyMw==
  size: 268800
ruby/ruby-1.9.3-p448.tar.gz:
  object_id: 683d6ee6-5f27-4fbd-a0ad-d4a5b333b64c
  sha: !binary |-
    YzdmNzM2ZTNiYzFjYTFlNjYxOWE5MTIxODM3ZGQwODQwYWFkNzdjZQ==
  size: 12559260
ruby/rubygems-2.0.7.tgz:
  object_id: fc782cb1-f279-4f52-b2c3-3ac61d1abb55
  sha: !binary |-
    ZjBiMGEwM2Q1NzNlMjExMjViYTVkYTFkYjE0NDYxZDZhOTkzNDBkNA==
  size: 337146
